apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  namespace: petclinic
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: petclinic.local
      http:
        paths:
          - path: /petclinic/
            pathType: Prefix
            backend:
              service:
                name: petclinic-backend
                port:
                  number: 9966
          - path: /
            pathType: Prefix
            backend:
              service:
                name: petclinic-frontend
                port:
                  number: 80
